name: Export Event-B Validation Results

on:
  push:
    paths:
    - 'eventB/Models/**'
    - 'eventB/Scenarios/**'

jobs:
  validation-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Updated to v2 for compatibility

      - name: Grant Execute Permissions
        run: |
          chmod +x eventB/CI-Testing/test-call-eventB.sh

      - name: Launch tests
        run: |
          ./eventB/CI-Testing/test-call-eventB.sh

      - name: Provide results for Event-B files
        uses: actions/upload-artifact@v3  # Updated to v3 for compatibility
        with:
          name: eventB-report
          path: eventB/Models/OP/Final_Output_eventB.txt