name: Export Validation Results

on:
  push:
    paths:
    - 'm1/petriNet/Models/**'
    - 'm1/eventB/Models/**'

jobs:
  validation-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Grant Execute Permissions
        run: |
          chmod +x m1/petriNet/CI-Testing/test-call-tina.sh
          chmod +x m1/eventB/CI-Testing/test-call-eventB.sh

      - name: Launch tests
        run: |
          ./m1/eventB/CI-Testing/test-call-eventB.sh
          ./m1/petriNet/CI-Testing/test-call-tina.sh

      - name: Provide results for Event-B files
        uses: actions/upload-artifact@v3  
        with:
          name: eventB-report
          path: m1/eventB/Models/OP/Final_Output_eventB.txt

      - name: Provide results for PetriNet (Tina) files
        uses: actions/upload-artifact@v3  
        with:
          name: tina-report
          path: m1/petriNet/Models/OP/Final_Output_tina.txt