name: Export Validation Results

on:
  push:
    branches:
      - master

jobs:
  validation-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Updated to v2 for compatibility

      - name: Grant Execute Permissions
        run: |
          chmod +x petriNet/CI-Testing/test-call-tina.sh
          chmod +x eventB/CI-Testing/test-call-eventB.sh

      - name: Launch tests
        run: |
          ./eventB/CI-Testing/test-call-eventB.sh
          ./petriNet/CI-Testing/test-call-tina.sh

      - name: Provide results for Event-B files
        uses: actions/upload-artifact@v3  # Updated to v3 for compatibility
        with:
          name: eventB-report
          path: eventB/Models/OP/Final_Output_eventB.txt
      
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Download Event-B Results
        uses: actions/download-artifact@v3
        with:
          name: eventB-report
          path: eventB-report

      - name: List Event-B Report Contents
        run: ls -R eventB-report
      
      - name: Debugging Commands
        run: |
          pwd
          echo "Contents of eventB-report:"
          ls -alR eventB-report
      
      - name: Display Current Directory
        run: pwd
    
      - name: Provide results for PetriNet (tina) files
        uses: actions/upload-artifact@v3  # Updated to v3 for compatibility
        with:
          name: tina-report
          path: petriNet/Models/OP/Final_Output_tina.txt
  
        